Repository purduesigbots/pros-cli, pull requests merged in 2019-12, with the labels that each got.

#114 Fix wireless terminal (RX only)
  pros/cli/common.py
  pros/cli/upload.py
  pros/serial/devices/vex/v5_device.py
Labels: enhancement, p: normal

#105 🐛 Fix user file upgrades
  pros/conductor/project/__init__.py
Labels: bug

#85 🐛 Use sys.exit correctly
  pros/cli/upload.py
Labels: bug, in testing, p: high

#77 🐛 Sort keys of cold hash
  pros/serial/devices/vex/v5_device.py
Labels: bug, p: low
