Repository purduesigbots/pros-cli, pull requests merged in 2019-02, with the labels that each got.

#49 👷‍♂️ Add wheel to Azure Artifacts
  azure-pipelines.yml
Labels: enhancement, p: normal

#48 ⚡ Add V5 upload compression
  pros/cli/upload.py
  pros/common/ui/__init__.py
  pros/conductor/project/__init__.py
  pros/serial/devices/vex/v5_device.py
  pros/serial/interactive/UploadProjectModal.py
Labels: in testing, optimization, p: high

#58 🚸 Add default directory support to NewProjectModal
  pros/cli/interactive.py
  pros/conductor/interactive/NewProjectModal.py
  pros/conductor/interactive/UpdateProjectModal.py
  pros/serial/interactive/UploadProjectModal.py
Labels: enhancement, in review, p: normal

#57 🚸 Add slot dropdown menu with knowledge of current programs
  pros/serial/devices/vex/v5_device.py
  pros/serial/interactive/UploadProjectModal.py
Labels: enhancement, in testing, p: normal

#26 🚸 Don't silently exit on no located port
  pros/cli/upload.py
Labels: enhancement, in progress, p: low

#60 🐛 Fix COBS packet parsing
  pros/serial/devices/vex/v5_user_device.py
Labels: bug, in testing, p: high

#55 🐛 Revert Terminal changes in #38
  pros/serial/terminal/terminal.py
Labels: bug, in testing, p: high

#46 ✨Add support for 🔥/❄ uploading
  pros/cli/upload.py
  pros/cli/v5_utils.py
  pros/conductor/project/__init__.py
  pros/serial/devices/system_device.py
  pros/serial/devices/vex/cortex_device.py
  pros/serial/devices/vex/v5_device.py
Labels: feature, in testing, p: normal

#56 ♻ Shadow upload command in upload-terminal
  pros/cli/upload.py
Labels: bug, in testing, p: high

#68 Patch Screen Cap Again
  pros/serial/devices/vex/v5_device.py
Labels: bug, in progress, p: normal

#66 🐛 Conductor Improvements
  pros/conductor/conductor.py
  pros/conductor/interactive/parameters.py
  pros/conductor/templates/template.py
Labels: bug, in testing, p: low

#47 ✨ 📶 Add wireless V5 uploading
  pros/serial/devices/vex/v5_device.py
  pros/serial/devices/vex/vex_device.py
  pros/serial/ports/direct_port.py
Labels: feature, in testing, p: normal

#69 Make SUPPRESSED_EXCEPTIONS work again for sentry
  pros/common/sentry.py
Labels: enhancement, p: low

#71 Clean up after all these merges
  pros/serial/devices/vex/v5_device.py
  pros/serial/interactive/UploadProjectModal.py
Labels: bug, p: unbreak now!

#72 🚸 Add ability to save upload options to project
  pros/serial/interactive/UploadProjectModal.py
Labels: enhancement, in progress, p: high

#67 🐧 ConnectionRefusedException for Linux as well
  pros/serial/ports/direct_port.py
  pros/serial/ports/exceptions.py
Labels: enhancement, p: normal
